### PR TITLE
Technical and user interface improvements

### PR DESCRIPTION
**Pull request by dpiparo**
Technical improvement: Make classes final where needed
User interface improvement: make user unable to create TActionResultPtr(Base) instances, default constructed or not.

### CODE REVIEW

**Comment by eguiraud** [comment]
nice!

two things on the second commit:
- now that I think of it, shouldn't `TActionResultPtrBase` actually be in `ROOT::Internal`? users never have to handle one, they only deal with concrete `TActionResultPtr` instantiations
- `GetActionResultPtr` is a bit confusing as a method name, sounds like a getter but it's actually a factory that also registers the object

**Comment by dpiparo** [comment]
Hi,
two replies to your two comments:
- The interface of TActionResultPtrBase is also not public. Now, since the beginning actually, I am not sure we can put part of the inheritance chain in the `Internal` namespace and part outside it. I guess it's a decision we may take. If distributing the chain among namespaces is not something we want, we may, for the `ROOT` namespace, go for a `_Myclassname_base` like convention (https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00965.html).
- I resonated with the widely known `TClass::GetClass` method perhaps. What about `MakeRegisteredActionResultPtr` ?

**Comment by eguiraud** [comment]
* fair enough, to be seen
* could be even just `MakeActionResult[Ptr?]`, as long as it does not look like a getter I do not have strong opinions

**Comment by eguiraud** [comment]
Since we are touching this logic anyway I think we should also tackle bug #63 :smile:

**Comment by dpiparo** [comment]
Point 1) has been solved as the `TActionResultPtrBase` class has been removed. Point 2) as well: the method has been called `MakeActionResultPtr`.
The constructors of `TActionResultPtr` are still private and, as a desirable side effect, #63 is solved.

**Pull request merged**
