### PR TITLE
Allow easy and safe use of array types as branches

### PR DESCRIPTION
**Pull request by eguiraud**
Opening a pull request for discussion and because there is still room for improvement.
If the `BranchType` is `TTreeReaderArray<T>` (or equivalently, via an alias, `Array<T>`) a `TTreeReaderArray` is built and passed to the filters instead of a `TTreeReaderValue`.<br>
`h1analysisDataFrame.C` seems to work well.

Things that can be improved:

- must use `[TTreeReader]Array<T>&` (reference) as branch type spec because `TTreeReaderArrays` cannot be copy-constructed while looping over events
- cannot use `const Array<T>&` as branch type spec because `TTreeReaderArray::operator[]` is not const
- this does not play well with the automatic detection `isContainer<BranchType>` as `TTreeReaderArray` is not a container. This means that these branches will not benefit of the special vector-friendly behaviours of actions such as `Fill`, that automatically loop over the elements of container-type branches

These issues would probably be solved by having an `Array` type that is a container (in the sense of our `IsContainer` check), can be copy-constructed, has a const `operator[]` and can be constructed from a `TTreeReaderArray&`.

### CODE REVIEW

**Comment by dpiparo** [comment]
Hi @bluehood ,

Nice code and great analysis of the problem.
I think one step forward here would be to use the `array_view` (discussed with @karies last week). When this is present in the signature of the lambda passed to a filter or a branch producer, we can build a `TTreeReaderArray` and pass it to  the view parameter.

Now coming to your points:

- must use `[TTreeReader]Array<T>&` (reference) as branch type spec because `TTreeReaderArray`s cannot be copy-constructed while looping over events
I guess here we need to test how the array_view can offer a view also on a reference.
- cannot use const `Array<T>&` as branch type spec because `TTreeReaderArray::operator[]` is not const
This by design: we want to deserialise on demand the minimum amount possible of data, for example in presence of split collections. So a call to `TTreeReaderArray::operator[]` has in general more effects than a simple jump. Now, I wonder if this is a problem. Being it a view, it can be passed by value, as one would do with string_view. Here we can be clear with our documentation and examples.
- this does not play well with the automatic detection `isContainer<BranchType>` as `TTreeReaderArray` is not a container. This means that these branches will not benefit of the special vector-friendly behaviours of actions such as Fill, that automatically loop over the elements of container-type branches
We fully control the `isContainer` branch type: we can bend its functionality to our needs. For example, see how we detect if we deal with a `vector<bool>` ;-)

**Comment by eguiraud** [comment]
Hello,
yes this was more of a first try to see what could be done than a full-fledged solution.

Something like `array_view` would probably help solving all three issues.

**Comment by Axel-Naumann** [comment]
I'll back-port `array_view` into v6. I'll try my best to make it C++11 compatible :-)

**Comment by eguiraud** [comment]
@karies thank you!

question: for which types is it strictly necessary to build a `TTreeReaderArray` rather than a `TTreeReaderValue`?

**Comment by eguiraud** [comment]
feature is now present in ROOT

**Pull request closed without merging**
