### PR TITLE
Add tracing (for now: filter acceptance) abilities.

### PR DESCRIPTION
**Pull request by Axel-Naumann**
Each filter reports how many events came in and how many passed.

Ideally this would keep some sort of hierarchy, to show cut flow branching. Also, its dumping interface is pretty heavy, maybe you have a better idea?

### CODE REVIEW

**Comment by eguiraud** [comment]
Thank you, cool and required feature :)

Accepting this at this time would cause major headaches when merging the current "testing" branch, which introduces multi-thread support and ROOT namespaces/naming conventions, among other things.
I will add another comment with some thoughts.

**Comment by eguiraud** [comment]
Here it is.

I think named filters are a very cool concept that might also turn out to be useful for things we do not imagine at the moment. Moreover, making this work with the multi-thread version of `TDataFrame` will be easy: in line with the rest of the code, `fAccepted` and `fRejected` should become vectors with as many slots as the number of TBB workers (which one can retrieve with `ROOT::GetImplicitMTPoolSize()`). `CreateSlots` is the method that takes care of resizing the vectors and is invoked before running the event-loop. We also have to make sure `fAccepted` and `fRejected` are evaluated once, and do not keep updating if the event loop is run more than once.

If I understand correctly users register filters to be traced by "baptising" them with the `Trace` method, and statistics are printed for named filters whenever the event-loop is run or `DumpAcceptanceTrace` is called on a `TDataFrameInterface` object.<br>
I think naiive users might get confused as to why their count is zero when they call `DumpAcceptanceTrace` on a filter object before the event loop has been run. Also users cannot easily trace filters in chains that do not end in an action, e.g. `d.Filter(cut).Trace("cut")` does nothing, `d.Filter(cut).Trace("cut").DumpAcceptanceTrace()` prints zeros. I would not allow `Trace` and `DumpAcceptanceTrace` to be called on `TDataFrameBranch` and `TDataFrame` objects.

I am thinking whether something like
```c++
auto report = d.Filter(cut, branchList, "filterName").Report();
report->Print();
```
could solve these issues. It would fit better with the programming model, would move the burden of implementing the `DumpAcceptance*` methods away from the filters and maaaaybe would help in building a cutflow branching/hierarchy report where the users can easily fine-tune what they want printed for each run.
```c++
// report on all filters upstream of the Report action
auto report = d.Filter(cut1).Filter(cut2).Report(kAll); // Report() is equivalent to Report(kNamed)
```
```c++
// report on named filters in both branches, taking care of printing common filters once
auto d2 = d.Filter(f1, "f1");
auto r1 = d2.Filter(f2, "f2").Report(kNamed, 1); // 1 indicates the report _group_ this report is part of
auto r2 = d2.Filter(f3, "f3").Report(kNamed, 1); // same report group, so r1 and r2 actually print the same thing
r1->Print(); // run event loop, print reports for all filters in this same report group 
```

What do you think?

**Comment by dpiparo** [comment]
Hi @bluehood, @karies,

coming to this a bit late.
I think the code can be easily adapted to the parallel execution making it "processing slot aware".
I like the 
`
auto report = d.Filter(cut, branchList, "filterName").Report();
report->Print();
`
form as it would make the name a property of the filter and `Report()` a method to book an action as `Histo`, `Mean` etc or, more precisely, `Count` since there is no input branch. The graph will have to be followed upwards until the original data frame after execution. Different reports for different cut flows can be obtained allowing to seamlessly study effects of cuts (e.g. pt > 15, 20 , 30, 35 GeV).

**Comment by Axel-Naumann** [comment]
`auto report = d.Filter(cut, branchList, "filterName").Report(); report->Print();` forces me to create lots of variables, both for the filter state and the reports (or can I chain Filter.Report.Filter?). Maybe better `d.Report()` after the (possibly implicit) `Run()`, reporting on the whole processing graph? We could still give access to specific filter's reports, even through that interface.

**Comment by dpiparo** [comment]
If we decide to make "Report" an action, nothing can hang from it, so no `Filter.Report.Filter`.
If `d.Report()` after running is allowed, this implies adding the method to the `TDataFrameInterface` which means that the user could call that also on filters/branches.
```c++
auto fd = d.Filter(...);
auto nb = fd.AddBranch(...);
fd.Report();
nb.Report; // ?
```

**Comment by eguiraud** [comment]
[Cutflow reports](https://trello.com/c/zzrAymbs/8-cutflow-reports)

**Comment by eguiraud** [comment]
I have a pull request with a second iteration of this ready for ROOT.
This is how it looks:
```c++
TDataFrame df;
a = df.Filter("0");
h1 = a.Filter("1").Histo();
h2 = a.Filter("2").Histo();
df.Report(); // prints nothing, filters have not run
h1->Draw();
df.Report(); // prints cutflow reports for Filter{0,1,2}
```

**Pull request closed without merging**
